language: python
dist: xenial
sudo: required

cache:
  - apt
  - pip

notifications:
  email:
    on_failure: never

before_install:
  - sudo apt-get update
  - sudo apt-get install -y chktex lacheck

install:
  - pip install -r requirements.txt

script:
  - mkdir statick_output; statick . statick_output --profile tex-profile.yaml
