---
name: Unit Tests

on: [pull_request, push]  # NOLINT

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: |
          python -m pip install --upgrade numpy
          python -m pip install --upgrade statick-tex
          sudo apt-get update
          sudo apt-get install chktex
          sudo apt-get install lacheck

      - name: Statick
        run: |
          statick . --check --user-paths statick_config --profile tex-profile.yaml

      - name: Compile PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mae283_lectures.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: mae283_lectures.pdf
